name: Push to GitHub
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "branch to push"
        required: true
        default: "main"
jobs:
  push_to_gh:
    name: Push to GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Clone from Codeberg
        run: git clone --branch "${{ inputs.branch }}" --single-branch https://codeberg.org/quizfreely/docs.git
      - name: Push to GitHub
        run: |
          cd docs
          git push https://ehanahamed:${{ secrets.GH_TOKEN }}@github.com/quizfreely/docs.git "${{ inputs.branch }}" --tags
